name: Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24" # Can also use 'latest'

      - name: Install dependencies
        run: npm ci # npm clean install

      - name: Run Unit Tests
        run: npm test # Run vitest tests
